### PR TITLE
change license

### PR DESCRIPTION
**Pull request by macrosak**
We need to make sure that all contributors agree with the change.

@kuceram can you write a comment here that you agree with the license change?

### CODE REVIEW

**Comment by macrosak** [comment]
OlivierKamers agrees as mentioned here: https://github.com/tadodotcom/grails-quick-search/pull/12#issuecomment-210821767

**Comment by kuceram** [comment]
@macrosak agree!

**Comment by EvertEt** [comment]
Great! Any idea when the grails plugin will be updated to the lastest master?

**Comment by macrosak** [comment]
@EvertEt hopefully this week. I am still waiting for a confirmation from one contributor: https://github.com/tadodotcom/grails-quick-search/pull/8

**Comment by macrosak** [comment]
@EvertEt @OlivierKamers plugin was finally approved and released: https://grails.org/plugin/quick-search

**Comment by OlivierKamers** [comment]
Great news, thanks!

**Pull request merged**
